# Generated by Django 3.2.14 on 2023-05-11 19:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('s_name', models.CharField(blank=True, max_length=20)),
                ('f_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('m_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Middle Name')),
                ('l_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=50)),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField()),
                ('position', models.CharField(max_length=150)),
                ('educ_background', models.TextField()),
                ('highest_deg_attain', models.CharField(max_length=150)),
                ('course', models.CharField(max_length=150)),
                ('school_grad', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=150)),
                ('subject_coordinator', models.CharField(max_length=150)),
                ('contact_no', models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(15)], verbose_name='Contact No')),
                ('date_hired', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fk_profile_detail_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
