# Generated by Django 3.2.14 on 2023-05-11 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_portal', '0002_profiledetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiledetail',
            name='highest_deg_attain',
        ),
    ]
