# Generated by Django 3.2.14 on 2023-05-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_portal', '0003_remove_profiledetail_highest_deg_attain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiledetail',
            name='educ_background',
        ),
        migrations.AddField(
            model_name='profiledetail',
            name='highest_deg_attain',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
