# Generated by Django 3.2.14 on 2023-05-11 20:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_portal', '0004_auto_20230511_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetail',
            name='contact_no',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Contact No'),
        ),
    ]
