# Generated by Django 3.2.14 on 2023-05-14 09:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_portal', '0005_alter_profiledetail_contact_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('period_covered_from', models.DateField()),
                ('period_covered_to', models.DateField()),
                ('basic_ed', models.FloatField(default=0.0, null=True)),
                ('college', models.FloatField(default=0.0, null=True)),
                ('overload', models.FloatField(default=0.0, null=True)),
                ('substitution', models.FloatField(default=0.0, null=True)),
                ('overtime', models.FloatField(default=0.0, null=True)),
                ('holiday_pay', models.FloatField(default=0.0, null=True)),
                ('ndp', models.FloatField(default=0.0, null=True)),
                ('honorarium', models.FloatField(default=0.0, null=True)),
                ('longetivity', models.FloatField(default=0.0, null=True)),
                ('merit_incetive_pay', models.FloatField(default=0.0, null=True)),
                ('adj', models.FloatField(default=0.0, null=True)),
                ('rice', models.FloatField(default=0.0, null=True)),
                ('laundry', models.FloatField(default=0.0, null=True)),
                ('position', models.FloatField(default=0.0, null=True)),
                ('absences', models.FloatField(default=0.0, null=True)),
                ('tardiness_undertime', models.FloatField(default=0.0, null=True)),
                ('sss_prem', models.FloatField(default=0.0, null=True)),
                ('sss_loan', models.FloatField(default=0.0, null=True)),
                ('pag_ibig_prem', models.FloatField(default=0.0, null=True)),
                ('pag_ibig_loan', models.FloatField(default=0.0, null=True)),
                ('philhealt_prem', models.FloatField(default=0.0, null=True)),
                ('withholding_tax', models.FloatField(default=0.0, null=True)),
                ('landbank', models.FloatField(default=0.0, null=True)),
                ('damayan', models.FloatField(default=0.0, null=True)),
                ('salary_deductions', models.FloatField(default=0.0, null=True)),
                ('uniform', models.FloatField(default=0.0, null=True)),
                ('salary_loan', models.FloatField(default=0.0, null=True)),
                ('tuition_fee', models.FloatField(default=0.0, null=True)),
                ('snpl', models.FloatField(default=0.0, null=True)),
                ('lbp_adj', models.FloatField(default=0.0, null=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fk_payroll_detail_employee', to='teachers_portal.profiledetail')),
            ],
        ),
    ]
