# Generated by Django 3.2.14 on 2023-05-14 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_portal', '0006_payrolldetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PayrollDetail',
        ),
    ]
